set(INTERACTIVE_DIR "${SM_EXTERN_DIR}/interactive-cpp")

file(GLOB_RECURSE SMDATA_INTERACTIVE_FILES_SRC ${INTERACTIVE_DIR}/include/*.cpp)
file(GLOB_RECURSE SMDATA_INTERACTIVE_FILES_HPP ${INTERACTIVE_DIR}/include/*.h)

source_group("Interactive" FILES ${SMDATA_INTERACTIVE_FILES_SRC} ${SMDATA_INTERACTIVE_FILES_HPP})